blank_issues_enabled: false
contact_links:
  - name: Questions & Help 🙋
    url: https://github.com/BenjaminOddou/portfolio/discussions
    about: Please use Discussions for all additional questions or technical advice
